### ISSUE TITLE
Actual functionality of the game

### ISSUE THREAD

**Issue by MynahMarie** [FACN3/B12-subconsciousness#13]
The game needs to: 

- [x] allow for each card to be clicked
- [x] cards need to show face up when clicked
- [x] no more then 2 cards can be shown at the same time
- [x] if a match is found, the cards are taken out from the deck
- [x] if no match, the cards are flipped back face down
